### ISSUE TITLE
img element not updating on state change

### ISSUE THREAD

**Issue by lsnape** [jarohen/flow#1]
The atom updates and the enclosing `f/el` executes, but the `img` element in the DOM remains the same.

https://gist.github.com/lsnape/1d77d4d50cafe2fdbd51

**Comment by jarohen** [comment]
Thanks - as discussed, think this is a problem with multiple let bindings.

**Comment by jarohen** [comment]
Hey Luke - guessing this is solved by the b3 re-write? Haven't been able to duplicate this since...?

James

**Comment by lsnape** [comment]
Not completely certain but haven't seen it since the time I reported it.

**Comment by jarohen** [comment]
Cool - will close for now, feel free to re-open if you spot it in the new version.
