### ISSUE TITLE
f/root keeps appending

### ISSUE THREAD

**Issue by whodidthis** [jarohen/flow#10]
With react & co. remounting/rooting is used to rerender which translates to easy figwheel development (js-onload #(remount)).

Would this be possible in flow instead of appending on f/root?

https://github.com/whodidthis/flow-testing/blob/master/src/flow_testing/core.cljs#L54

**Comment by jarohen** [comment]
Sure, no worries, it's a bug I've just fixed so should go in with the next release (which will should be in the next day or so) 

Cheers, 

James

**Comment by jarohen** [comment]
I tell a lie - it should already be in 0.3.0-alpha3?

Thanks for checking out Flow btw - let me know if there's anything that would make it easier/anything you think's missing! 

James

**Comment by whodidthis** [comment]
Ok I did have misconfigured checkouts, thought I was running latest, but even with alpha3 `(do (remount) (remount))` results in two elements.

Also does `Uncaught TypeError: Cannot read property 'style' of null` ring any bells? Really wish I knew where that was coming from but figwheel loses the stack trace. Might be something unrelated though

Edit: the latter is probably something figwheel related dont worry about that

**Comment by jarohen** [comment]
No worries - was trying to work out the commit ordering on GitHub mobile so entirely possible I misread it - will check when I'm next in front of my computer. 

I've not seen that error before, would it be possible for you to post a snippet / sample project? 

James

**Comment by whodidthis** [comment]
Ok i think i confirmed the weird error a figwheel issue, sorry about that

**Comment by jarohen** [comment]
That's OK, thanks for reporting it - good to have it documented if someone else comes across it!
