### ISSUE TITLE
Inline styles

### ISSUE THREAD

**Issue by whodidthis** [jarohen/flow#11]
I started making an input and got stuck on how to make inline styles work in the f/el macro when behind a binding:
https://github.com/whodidthis/flow-testing/blob/master/src/flow_testing/input.cljs#L23
This line gives me `Don't know how to create ISeq from: clojure.lang.Symbol at line 21 src/flow_testing/input.cljs`

Additionally if this can work a similar method of giving conditional styles would be nice that classes have right now. Something like `::f/style [default-style (and hover hover-style) (and focus focus-style)]` so those single-depth maps would just merge.

React has a similar plan for inline styles: https://github.com/reactjs/react-future/blob/master/04%20-%20Layout/04%20-%20Inline%20Styles.md#using-styles

**Comment by jarohen** [comment]
Ah - this is a problem that Flow parses `::f/style` at compile time, and expects a map - so only a literal map works here (for now) I'm afraid.

Conditional styles sounds like a good idea - will take a look at the link you posted and see what could be possible.

James

**Comment by whodidthis** [comment]
Although now that i think about it inline styles also had another problem with css and maps. Some css values are vendor prefixed like `display: flex; display: -webkit-flex;` that cant be expressed in a map.

Would require something like garden uses https://github.com/noprompt/garden#auto-prefixing so maybe better off using regular :style with wanted styles behind a transform-to-string function.

**Comment by jarohen** [comment]
Hmm - thinking about it, if I have CSS that's beyond basic KVs, it's usually enough to make me think about naming it as a CSS class, and having the CSS rendered by Garden as a separate stylesheet anyway - Flow's support for conditional classes is pretty good. Not sure what the current 'best practice' is on this - I always thought it was to keep the page markup as semantic as possible, but have seen a couple of React presentations where they seem to advocate putting CSS inline - do you have any opinions on it?

**Comment by whodidthis** [comment]
Inline styles would make it possible to get the entire view to a user in the first round trip when server side rendered. 

Too bad it does seem really difficult to work with vendor prefixes and the fact that media queries require classes.
